const Vehicle = {
  id: "id",
  created_by: {
    his_name: "created_by",
    id: "id",
    username: "username",
    first_name: "first_name",
    middle_name: "middle_name",
    last_name: "last_name",
    is_staff: "is_staff",
  },
  owner_name: "owner_name",
  plate_number: "plate_number",
  chassis_number: "chassis_number",
  model: "model",
  color: "color",
  documentation_type: "documentation_type",
  documentation_ID: "documentation_ID",
  source: "source",
  address: "address",
  notes: "notes",
  status: "status",
  qr_code: "qr_code",
  documentaions_image: "documentaions_image",
  created_at: "created_at",
  updated_at: "updated_at",
  council: "council",
  category: "category",
  created_at_start: "created_at_start",
  created_at_end: "created_at_end",
  updated_at_start: "updated_at_start",
  updated_at_end: "updated_at_end",
};

const VehicleTranslated = {
  id: "رقم الآلية",
  created_by: {
    his_name: "أنشئ بواسطة",
    id: "رقم المستخدم",
    username: "اسم المستخدم",
    first_name: "الاسم الاول",
    middle_name: "الاسم الاوسط",
    last_name: "الاسم الاخير",
    is_staff: "موظف؟",
  },
  owner_name: "اسم المالك",
  plate_number: "رقم اللوحة",
  chassis_number: "رقم الهيكل",
  model: "المودل",
  color: "اللون",
  documentation_type: "نوع الوثيقة",
  documentation_ID: "رقم الوثيقة",
  documentaions_image: "الوثيقة",
  source: "المصدر",
  address: "العنوان",
  notes: "ملاحظات",
  status: "الحالة",
  qr_code: "الباركود",
  created_at: "أنشئ بتاريخ",
  updated_at: "عدل بتاريخ",
  council: "المجلس",
  category: "الفئة",
  created_at_start: "أنشئ من تاريخ",
  created_at_end: "أنشئ إلى تاريخ",
  updated_at_start: "عدل من تاريخ",
  updated_at_end: "عدل إلى تاريخ",
};
export { Vehicle as default, VehicleTranslated };
